git rm Diagram1.png
git rm frequency_minim.png
git rm gold_dispersion.png
git rm gold_minim.png
git rm thermal_expansion.png
git rm 5000_Temp_Freq.png
git rm 5000_Temp_Omeg.png
git rm Conf_Freq.png
git rm Figure_1_N.png
git rm Figure_2.png
git rm Figure_2_N.png
git rm Hands-on3.dia
git rm Hands-on3.png
git rm Old_Conf_Freq.png
git rm dispersion.png
git rm second_order.png
git rm F.png
git rm Fig1.png
git rm Fig10.png
git rm Fig2.png
git rm Fig3.png
git rm Fig4.png
git rm Fig5.png
git rm Fig6.png
git rm Fig7.png
git rm Fig8.png
git rm Fig9.png
git rm G_spectrum.png
git rm NoMM_Spectral.png
git rm convergence.png
git rm dynamic_X.png
git rm freq.png
git rm spec_path.png
git rm static_X.png
git rm static_path.png
git rm a2F_PdH.pdf
git rm gap_PdH.pdf
git rm SSCHA_Logo_original_bertikala.png
git rm SSCHA_epiq_Logo.png
git rm fs_mgb2.png
git rm logo_epiq.png
git rm lw.png
git rm mos2.png
git rm qr-code-epiq-both.png
git rm sampling.png
git rm wannier.png
git rm wannier_interpolation.png
git rm workflow.png
